version: '3.8'

services:
  db:
    image: postgres:11
    volumes:
      - /tmp/sof21/db:/var/lib/postgresql/data
    restart: always
    ports:
    - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres

  mailcatcher:
    image: dockage/mailcatcher
    ports:
    - "1080:1080"

  backend:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails db:setup && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - /tmp/sof21/railtmp:/app/tmp
    ports:
    - "3000:3000"
    depends_on:
      - db
      - mailcatcher
    environment:
      LOCAL_MAILSERVER: 'true'
      RAILS_ENV: 'development'

